### ISSUE TITLE
WISE: Release new development version for testing

### ISSUE THREAD

**Issue by nealmcloughlin** [WISE-Developers/Project_issues#124]
Work completed for the Pre-WISE sprint has been assigned for testing, but there is no version to test. This task is to build a new development version for testing with the work completed for the Pre-WISE sprint.

**Comment by spydmobile** [comment]
@RobBryce @nealmcloughlin @BadgerOnABike 
Please indicate all issues that this build will be used for testing.

**Comment by spydmobile** [comment]
@RobBryce @BadgerOnABike @nealmcloughlin ok, lets try this again, who needs a build and why?

**Comment by BadgerOnABike** [comment]
I believe anything labelled with the PRE-WISE epic would be included for testing. That's the only build I know of that is ready for testing. So, with that, all issues that are labelled pre-wise as that spring has been completed and those items are ready for testing.

**Comment by nealmcloughlin** [comment]
The development team needs a build so that work completed in the Pre-WISE sprint can be tested and closed. We need builds for both version 6 and 7 of PSaaS/WISE so that validation testing can be completed in #126. We do not need a build of Prometheus or REDapp.

**Comment by RobBryce** [comment]
New builds (2022.12.00) of Prometheus and WISE are uploaded.  Note that no renaming has occurred yet, so the executables still say PSaaS.

I've tested the Windows Prometheus installer, and for it to succeed with Bitdefender installed, I had to run it as Administrator.  Otherwise, the anti-virus software kills the installer when registry entries are to be added for the COM DLL's.  Bitdefender also reports that the Windows installers are "clean".
